version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
        environment:
          GO111MODULE: "on"

    working_directory: /go/src/github.com/akdilsiz/go-phoenix-socket-client
    steps:
      - checkout
      - run: sleep 5
      - run: go get -v -t -d ./...
      - run: sleep 5
      - run: go test -v -coverprofile=coverage.txt -covermode=atomic ./...
      - run: bash <(curl -s https://codecov.io/bash)